'use client';

import { use, useEffect, useState } from 'react';
import Markdown from 'react-markdown';
import { Button, Badge, Rating } from '@/components';
import { fetchSiteBySlug } from '@/lib/firebase/sites';
import type { SiteWithReview } from '@/lib/types';
import styles from './page.module.css';

interface ReviewPageProps {
    params: Promise<{ slug: string }>;
}

export default function ReviewPage({ params }: ReviewPageProps) {
    const { slug } = use(params);
    const [site, setSite] = useState<SiteWithReview | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        async function loadSite() {
            try {
                const data = await fetchSiteBySlug(slug);
                setSite(data as SiteWithReview);
            } catch (err) {
                console.error('Failed to load site:', err);
            } finally {
                setLoading(false);
            }
        }
        loadSite();
    }, [slug]);

    if (loading) return <div className={styles.page}><p>Loading review...</p></div>;

    if (!site) {
        return (
            <div className={styles.page}>
                <div className={styles.notFound}>
                    <h1>Review Not Found</h1>
                    <p>This site hasn&apos;t been reviewed yet or doesn&apos;t exist.</p>
                    <Button href="/sites">Browse Sites →</Button>
                </div>
            </div>
        );
    }

    const review = site.review;
    const screenshotUrl = site.crawlData?.screenshotUrl;

    return (
        <div className={styles.page}>
            {/* Hero */}
            <header className={styles.hero}>
                <div className={styles.heroMeta}>
                    <Badge variant="primary">{site.category}</Badge>
                    {site.isNew && <Badge variant="new">New</Badge>}
                    {site.isPremium && <Badge variant="premium">Premium</Badge>}
                </div>
                <h1 className={styles.title}>{review?.title || site.name}</h1>
                <p className={styles.excerpt}>{review?.excerpt || site.description}</p>
                <div className={styles.ratingBox}>
                    <span className={styles.ratingScore}>{site.rating.toFixed(1)}</span>
                    <span className={styles.ratingMax}>/10</span>
                    <Rating score={site.rating} showScore={false} />
                </div>
            </header>

            {/* Screenshot */}
            <div className={styles.screenshotWrap}>
                {screenshotUrl ? (
                    <img src={screenshotUrl} alt={`${site.name} screenshot`} className={styles.screenshot} />
                ) : (
                    <div className={styles.screenshotPlaceholder}>
                        <span>📸</span>
                        <p>Screenshot not available</p>
                    </div>
                )}
            </div>

            {/* Review Content */}
            <section className={styles.content}>
                <div className={styles.prose}>
                    {review?.content ? (
                        <Markdown>{review.content.replace(/\\n/g, '\n')}</Markdown>
                    ) : (
                        <>
                            <p>{site.description}</p>
                            <p><em>Full AI review coming soon...</em></p>
                        </>
                    )}
                </div>
            </section>

            {/* Pros/Cons */}
            <section className={styles.proscons}>
                <div className={styles.prosBox}>
                    <h3 className={styles.boxTitle}>👍 Pros</h3>
                    <ul className={styles.boxList}>
                        {review?.pros?.length ? (
                            review.pros.map((pro, i) => <li key={i}>{pro}</li>)
                        ) : (
                            <li>Pros will be generated by AI</li>
                        )}
                    </ul>
                </div>
                <div className={styles.consBox}>
                    <h3 className={styles.boxTitle}>👎 Cons</h3>
                    <ul className={styles.boxList}>
                        {review?.cons?.length ? (
                            review.cons.map((con, i) => <li key={i}>{con}</li>)
                        ) : (
                            <li>Cons will be generated by AI</li>
                        )}
                    </ul>
                </div>
            </section>

            {/* Verdict */}
            <section className={styles.verdict}>
                <h2 className={styles.verdictTitle}>🔥 The Verdict</h2>
                <p className={styles.verdictText}>
                    {review?.content ? 'Check out the full review above!' : 'AI verdict coming soon...'}
                </p>
                <Button href={site.url} size="lg">Visit {site.name} →</Button>
            </section>
        </div>
    );
}
